version: '3.8'

services:
  api:
    build:
      context: .
    ports:
      - "8000:8000"
    depends_on:
      - db

  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_PASSWORD: Password123
      POSTGRES_DB: mun
    volumes:
      - postgres-data:/var/lib/postgresql/data

  adminer:
      image: adminer
      restart: always
      ports:
        - 8080:8080

volumes:
  postgres-data:
