version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile  # Path to your Dockerfile for the FastAPI app
    ports:
      - "8000:8000"  # Expose FastAPI app on port 8000
    volumes:
      - db-data:/app/db
    environment:
      - ENVIRONMENT=development  # Set to production for prod environment

volumes:
  db-data: